application: php-p3
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /img
  static_dir: img
  
- url: /css
  static_dir: css

# Serve php scripts.
- url: /(.+\.php)$
  script: \1
  
- url: /.*
  script: index.php
  